---
title: "Seminar 5"
author: "Uyen"
date: "0/10/2020"
output: html_document
---

```{r setup, echo = FALSE, include=TRUE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning=FALSE)
```

``` {r libraries}
library(dplyr)
library(tidyverse)
library(here)
library(DataCombine)
library(lme4)
library(ggrepel)
```

```{r loaddata, include=TRUE, cache=TRUE}
dict_path <- here("capstone20_dictionaries.csv")  
wordcount_path <- here("dictionary_word_matrix_adj.csv") 
coun_lang1_path <- here("CIA fact sheet-2.csv")
disease_path <- here("Disease_Incidences.csv")
population_path <- here("World_population.csv")
geographical_path <- here("Cultural-Clusters.csv")
```

```{r PANAS-dataset, include=TRUE, warning= FALSE}
#create PANAS dataset
dict <- read_csv(dict_path, col_types = cols(id = col_character()) ) 

adjcount <- read_csv(wordcount_path,  col_types = cols(id = col_character(), 
                                                       year= col_integer(), 
                                                       title = col_character(), 
                                                       langname = col_character(), 
                                                       gcode = col_character(), 
                                                       area = col_character(), 
                                                       langfamily = col_character(), 
                                                       affiliation = col_character(), 
                                                       .default=col_double()))  %>% 
  mutate(dictsize = select(., abbreviated:zealous) %>% apply(1, sum, na.rm=TRUE)) 

positive_words <- c("active","alert","attentive","enthusiastic","excited","interested","proud","happy", "joyful","delighted","cheerful","lively","energetic","strong","confident","bold","daring","fearless")
negative_words <- c("afraid","scared","nervous","jittery","irritable","hostile","guilty","ashamed","upset", "distressed","frightened","shaky","angry","disgusted","sad","lonely")


word_count <- adjcount %>% 
  select(id, all_of(positive_words), all_of(negative_words), dictsize) %>% mutate_all(~replace_na(.x, 0))

unit <- 10000

word_frequencies <- dict %>% 
 inner_join(word_count, by="id") %>%
  filter(dictsize >= 5000)

for (word in c(positive_words, negative_words))
{word_frequencies <- word_frequencies %>% mutate(!!sym(word) :=  unit * !!sym(word)/dictsize)}

word_frequencies$mean_positive<-rowSums(word_frequencies[,positive_words])
word_frequencies$mean_negative<-rowSums(word_frequencies[,negative_words])

panas_frequencies <- aggregate(word_frequencies, by = list(language = word_frequencies$langname),FUN = mean)

panas_frequencies <- panas_frequencies %>% select(language, mean_positive, mean_negative)

```

Change language names to match CIA and dictionary dataset
```{r CIA-dataset, include=TRUE,  warning= FALSE}

coun_lang1 <- read_csv(coun_lang1_path)

replaces <- data.frame(from = c("Albanian", "Bosnian", "Khmer", "Croatian", "Serbian", "Arabic", "Mandarin", "Persian", "Mongolian", "Greek", "Hebrew", "Armenian", "Malay", "Kyrgyz"), 
                       to = c("Northern Tosk Albanian", "Serbian-Croatian-Bosnian", "Central Khmer", "Serbian-Croatian-Bosnian", "Serbian-Croatian-Bosnian", "Standard Arabic", "Mandarin Chinese", "Western Farsi", "Halh Mongolian", "Modern Greek", "Modern Hebrew", "Eastern Armenian", "Standard Malay", "Kirghiz"))

coun_lang <- FindReplace(data = as.data.frame(coun_lang1), 
                         Var = "Language", 
                         replaceData = replaces, 
                         from = "from", to = "to", exact = TRUE)
```

Joining Cultural clusters, CIA, MH prevalence and PANAS

```{r Merge-all,  include =TRUE, warning= FALSE}
mh <- read_csv(disease_path)
population <- read.csv(population_path)
geographical_region <- read_csv(geographical_path) 

#merge cultural cluster & CIA factsheet
cul_lang <- merge(x = geographical_region, y = coun_lang, 
               by.x = "country", by.y = "Country", all = FALSE)

replaces2 <-data.frame(from = c("Myanmar", "Congo", "Czech Republic", 
                                "Russian Federation", "Taiwan, Province of China", 
                                "Virgin Islands, U.S."), 
                       to = c("Burma", "Republic of the Congo", "Czechia", 
                              "Russia", "Taiwan", "Virgin Islands"))

mh <- FindReplace(data = as.data.frame(mh),
                  Var = "location", replaceData = replaces2,
                  from = "from", to = "to", exact = TRUE)

population <- FindReplace(data = as.data.frame(population), 
                          Var = "location_name", replaceData = replaces2,
                          from = "from", to = "to", exact = TRUE)
population <- population %>% mutate_at(vars(starts_with("val")), funs(round(., 0)))

#merge incidence rates & total population
incidence <- mh %>%   select(location, val, cause) %>% 
  filter(!cause == "Dysthymia")%>%
  rename(incidence_count = val)

world_pop <- population %>% 
  filter(age_group_id == "22" & year_id == "2017" & sex_id =="3") %>%
  rename(total_pop = val)%>%
  select(location_name, total_pop)

disease_pop <- merge( x= incidence, y=world_pop, 
                      by.x = "location", 
                      by.y = "location_name")

Cul_lang_pop <- merge(x= cul_lang, y = disease_pop, 
                      by.x = "country", 
                      by.y = "location")

d <- merge(x= Cul_lang_pop, y = panas_frequencies, 
           by.x = "Language", 
           by.y = "language")

```

```{r dataset}
d1 <- d %>% group_by(country)%>% 
  mutate(mean_positive = weighted.mean(mean_positive, Percentage/100)) %>%
  mutate(mean_negative = weighted.mean(mean_negative, Percentage/100)) %>%
  mutate(Percentage = sum(Percentage)/2) %>% 
  subset(select = -c(Language))%>%
  distinct()

#Exclude country with <80% language accounted for
d2 <- d1 %>% 
  subset(Percentage >= 80) %>% 
  subset(select = -c(Percentage))%>% 
  mutate(total = mean_negative + mean_positive)

d_wide <- d2 %>% 
  pivot_wider(names_from = "cause", values_from="incidence_count")%>%
  rename(c("major_depressive_disorder"="Major depressive disorder",
           "anxiety_disorders" = "Anxiety disorders"))%>%
  filter(country != "Georgia" | total_pop < 5000000)%>%
  mutate_at(vars(starts_with("anxiety")), funs(round(., 0)))%>%
  mutate_at(vars(starts_with("major")), funs(round(., 0)))
```

Control variable



## Exploratory Plots
```{r, include=TRUE}
plotd <- d_wide %>% 
  mutate(AD_incidence = anxiety_disorders/total_pop,
         MDD_incidence = major_depressive_disorder/total_pop) 

plotd %>% ggplot(mapping = aes(y= AD_incidence, x= total))+
  geom_point()+
  geom_smooth(method = lm)+
  theme_bw()+
  labs(title= "Relationship between emotion words and Anxiety Disorder prevalence",
       y="Anxiety Disorder prevalence", x="Emotion word counts per 10000")

plotd %>% ggplot(mapping = aes(y= MDD_incidence, x= total))+
  geom_point()+
  geom_smooth(method = lm)+
  theme_bw()+
  labs(title= "Relationship between emotion words and Major Depressive Disorder prevalence",
       y="Major Depressive Disorder prevalence", x="Emotion word counts per 10000")
```

```{r, include=TRUE}
plotd %>% 
  ggplot(mapping = aes(x= AD_incidence, y= total, colour=cluster))+
  facet_wrap (~cluster, scales = "free") +
  geom_point(show.legend = FALSE)+
  geom_smooth(method=lm, show.legend = FALSE)+
  scale_colour_brewer(palette = "Set1")+
  theme_bw()+
  labs(title= "Relationship between Anxiety Disorder and emotion words by Cultural Cluster",
       x="Anxiety Disorder prevalence", y="Emotion words per 1000")

plotd %>% 
  ggplot(mapping = aes(x= MDD_incidence, y= total, colour=cluster))+
  facet_wrap (~cluster, scales = "free") +
  geom_point(show.legend = FALSE)+
  geom_smooth(method=lm, show.legend = FALSE)+
  scale_colour_brewer(palette = "Set1")+
  theme_bw()+
  labs(title= "Relationship between Major Depressive Disorder and emotion words by Cultural Cluster",
       x="MDD prevalence", y="Emotion words per 1000")
```


##Statistical Analysis - Mixed Model Regression
```{r MD regression, include=TRUE}
# We found a study that group countries based on cultural clusters (Mensah, Y. M., & Chen, H. Y. (2013). Global clustering of countries by culture–an extension of the GLOBE study.) and we will use this cultural cluster as our random effect for the analysis. 


FullDepressionModel <- glmer(cbind(major_depressive_disorder, total_pop - major_depressive_disorder) ~ total + (1|cluster), data = d_wide, family = binomial, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

beta_temp <- round(coef(summary(FullDepressionModel))[2,"Estimate"], 2)
show(FullDepressionModel)

ReducedDepressionModel <- glmer(cbind(major_depressive_disorder, total_pop - major_depressive_disorder) ~ (1|cluster), data = d_wide, family = binomial, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 1000000)))

a1<-anova(FullDepressionModel,ReducedDepressionModel)
p_value <-  signif(a1$"Pr(>Chisq)"[2] , digits=3)
chi_sq <- signif(a1$Chisq[2], digits=3)
df <- a1$Df[2]
show(a1)
show(warnings)
```

```{r AD regression}
FullADModel <- glmer(cbind(anxiety_disorders, total_pop - anxiety_disorders) ~ total + (1|cluster), data = d_wide, family = binomial, control=glmerControl(optimizer="bobyqa"))

beta_temp <- round(coef(summary(FullADModel))[2,"Estimate"], 2)
show(FullADModel)

ReducedADModel <- glmer(cbind(anxiety_disorders, total_pop - anxiety_disorders) ~ (1|cluster), data = d_wide, family = binomial, control=glmerControl(optimizer="bobyqa"))

a2<-anova(FullADModel,ReducedADModel)
p_value <-  signif(a2$"Pr(>Chisq)"[2] , digits=3)
chi_sq <- signif(a2$Chisq[2], digits=3)
df <- a2$Df[2]
show(a2)
```


